### ISSUE TITLE
Is there any way to avoid duplicate job?

### ISSUE THREAD

**Issue by navneetpandey** [yoomoney/db-queue#22]
How to avoid duplicate creation of job based on "payload"? In other words, the requirement is if there is already a task running with same "payload" , it should not be scheduled/accepted in queue.

**Comment by f0y** [comment]
We have similar use cases. I suggest you put this queue in a separate table and make an index on the payload field. 
Then you write custom DAO with a method like `select count(1) from queue_table where payload=?`.
Check whether there is already the same task in the queue before you put one.

There will be some performance degradation due to usage of the index on the payload field.
That is the reason why this behavior does not have native support.
